
services:
  - type: web
    name: safarsathi-backend
    env: docker
    plan: free
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        value: mongodb+srv://seamlesstrackers:aryan45637@safarsathi.ps7ngvv.mongodb.net/Rahasathi?retryWrites=true&w=majority
