spring.application.name=safarsathibackend
spring.data.mongodb.uri=mongodb+srv://seamlesstrackers:aryan45637@safarsathi.ps7ngvv.mongodb.net/Rahasathi?retryWrites=true&w=majority

server.port=8080
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=*
